### ISSUE TITLE
If the script can't place the columns, it gets in an infinite loop

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact-tools#104]
Tables with too many columns or rows that don't fit on one page cause the script to runaway -- 

![image](https://cloud.githubusercontent.com/assets/6181441/15841768/8211bbee-2c08-11e6-87a3-acb6f5872c5f.png)

@jmhauck i'm just going to drop this one in the backlog for the moment -- we can figure out what to do about this whenever you circle back on env analysis

**Comment by jessnoo** [comment]
add check for this condition and throw error that there are too many columns for the space provided

**Comment by jmhauck** [comment]
Here are the error messages I have in there right now when this condition is hit. Please let me know if you would like something else.

> 'Unable to process the data.'
> 'The width required to display the data exceeds the potential display area.'
> 'Please reduce the number of fields or provide a larger content display area in the layout template.'

**Comment by jessnoo** [comment]
I'm still seeing this issue ... 
![image](https://cloud.githubusercontent.com/assets/6181441/17117325/7f388dd8-5270-11e6-9942-6a20f3857b87.png)

Repro --
made a selection of conservation areas
passed the layer into the Impact Report tool
appeared to be stuck in loop

Test data:
[Issue104.gdb.zip](https://github.com/Esri/environmental-impact-tools/files/382455/Issue104.gdb.zip)

**Comment by jmhauck** [comment]
This shows a different case than what I was testing for. I didn't have a check in there that would evaluate when we had a single value; that when wrapped, would exceed the potential display height.

**Comment by jessnoo** [comment]
@jmhauck is this expected -- the "error on line" and "error in file name" and "with error message" lines?

![image](https://cloud.githubusercontent.com/assets/6181441/17121177/89ea7334-5286-11e6-99f0-7c51e8e23916.png)

if so, i'd like to rejiggy how the error messages are reported if possible.

**Comment by jmhauck** [comment]
@jessnoo yes that is expected. 

We could just remove the "error on line" and "error in file name" and "with error message" lines from the messages. Would that be sufficient?

**Comment by jmhauck** [comment]
Those lines can at times be helpful when debugging. I switched them to just print rather than add GP error messages. This same failure would now look like this:

![error](https://cloud.githubusercontent.com/assets/2170893/17144378/c8b1d200-5313-11e6-96e0-a3cdb321b3df.png)

Let me know if you want something else.

**Comment by jessnoo** [comment]
@jmhauck in this case since we are catching a known error, the way the information was displayed in the error message content was confusing -- like -- are these extra messages related to the width stuff or not?

thank you for the additional context -- i think what would be good is to keep the information but adjust the way it's presented in the messages.

+ a question about -- if the user is processing many tables -- can we also report which table is failing?

What about something like... 
"Error: Unable to process the **** table (File Name Info.py, <line number>, <error message>)
The width required to display the data exceeds the potential display area.
Please reduce the number .... "

?

**Comment by jmhauck** [comment]
@jessnoo good idea on the table name! I had shifted the filename, linenumber and additional error message to only print so you could still see them when debugging from an IDE. I can add them back as GP messages if you think they'll help rather than confuse.

**Comment by jessnoo** [comment]
@jmhauck so long as the specific error information is put in to context (unable to process table) -- i think it's ok.  because it came after the directive stuff, it was confusing to me because i didn't know if everything was related -- putting the specific error information inline with our messaging, i think it should be ok.  if it's going to be in red -- we need to say Error, etc etc

**Comment by jessnoo** [comment]
verified -- looks good -- thank you!
