### ISSUE TITLE
Report should show domain descriptions

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact-tools#109]
When fields being reported have domains - the report should show the domain description, not field value.

For example (from Incident Status Dashboard download) -- 

in the report: 
![image](https://cloud.githubusercontent.com/assets/6181441/16346823/375f75d8-39fe-11e6-84f0-98c770a5302b.png)

in the pop up -- notice MRP Status and NIMS Resource have descriptive values
![image](https://cloud.githubusercontent.com/assets/6181441/16346837/489ac21c-39fe-11e6-9df5-b5abed9c3a35.png)

**Comment by jessnoo** [comment]
Get a KeyError with the MRPs -- 

GP Error:
![image](https://cloud.githubusercontent.com/assets/6181441/17116322/213854ce-526c-11e6-9823-b03742e48657.png)


Table Properties:
![image](https://cloud.githubusercontent.com/assets/6181441/17116334/327858ec-526c-11e6-92a0-cace40fba18c.png)


Sample Data:
[Issue109.gdb.zip](https://github.com/Esri/environmental-impact-tools/files/382413/Issue109.gdb.zip)

**Comment by jmhauck** [comment]
I didn't have the domain object list setup correctly to deal with multiple domains for a single table.

**Comment by jessnoo** [comment]
looks good!
verified
