### ISSUE TITLE
Runtime Error with some datasets

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact-tools#114]
Not sure if this related to the columns or not -- 

![image](https://cloud.githubusercontent.com/assets/6181441/17116565/361fede2-526d-11e6-98b3-1aa137095f81.png)

tried with all columns and also just a subset, will attach the data once i get an issue number 

here's the column subset i also tried:
![image](https://cloud.githubusercontent.com/assets/6181441/17116610/791b0e24-526d-11e6-9abf-f3e34e92c127.png)

**Comment by jessnoo** [comment]
Test Data:

[Issue114.gdb.zip](https://github.com/Esri/environmental-impact-tools/files/382439/Issue114.gdb.zip)

**Comment by jessnoo** [comment]
looks like it's still failing -- on line 1204 now -- 

![image](https://cloud.githubusercontent.com/assets/6181441/17121133/454efc0e-5286-11e6-81af-cc9d6e8e34d8.png)

testing on Pro 1.3

**Comment by jmhauck** [comment]
@jessnoo could you ping me when you get in? I have tried with the sample data with the fields you mention above and I'm not getting an error. Want to see if we can nail down whatever I'm missing.

**Comment by jmhauck** [comment]
This is line 1204:

`domain_list = arcpy.da.ListDomains(workspace)`

I wonder what you'd see if you tried the same line against that workspace directly in the python window at the same point you see this error from the report tool.

**Comment by jessnoo** [comment]
upon closer inspection, this is related to feature classes used as input that are in a Feature Dataset -- need to check for this  when getting domains.

**Comment by jessnoo** [comment]
verified
