### ISSUE TITLE
Impact Report tool result has wider lines than expected

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact-tools#120]
With the baked in and alternate layout files, the horzLine and vertLine graphics are coming through in the resulting pdf wider than expected.

It seems like this may be related to the number of columns -- 

With Two Columns
![image](https://cloud.githubusercontent.com/assets/6181441/20499933/64be2d8e-afe8-11e6-8144-33818fcc32e7.png)

With Four Columns
![image](https://cloud.githubusercontent.com/assets/6181441/20499947/7a9dfd8c-afe8-11e6-9840-dcd2671ccdb4.png)

with many more... 
![image](https://cloud.githubusercontent.com/assets/6181441/20499994/9bc02c9c-afe8-11e6-813c-4f676cb54abc.png)

Tested with Pro Alpha 4

Exporting the template layout files does not result in this behavior -- it seems specific to what our tool is doing with the layout.

**Comment by jmhauck** [comment]
@jessnoo looks like a Pro bug.

Steps to reproduce:

1) Create a new Pro project
2) Insert > New Layout 8.5 x 11
3) Insert > Line > Common > Black (0.5pt)
4) Draw a vertical line on the layout
5) From the Contents Pane > right-click the Line element > Properties
6) Click Symbol > Properties > Appearance and notice the width of the line is .5
7) Click Line Symbol > Placement and adjust the height to be 10 for example
8) Repeat step 6 and notice that the width is now different than .5
9) Repeat step 7 but adjust to a height of 1
Continually adjust the height between  10 and 1 and notice that the width automatically grows
The same would also be seen if you draw a horizontal line and adjust the width of the line element.

Just as a note:

We got on the phone with Jeff B. from the Layout team and they are going to enter a CR...will reference here as soon as we get it.

In case it comes up I am unaware of a way to workaround this as the GraphicElement API does not expose a way to access the symbol and we don't have any API to create new Symbols.

**Comment by jmhauck** [comment]
Here is the Change Request: 348,821 and the WRR: http://desktopqa/WarRoom/ProApp/Requests/Edit/PublicDraft/22158

**Comment by jessnoo** [comment]
Validated core fix with build 7131
