### ISSUE TITLE
Report table formatting is unexpected (Pro 2.2 Testing)

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact-tools#127]
When testing the Environmental Analysis project for 2.2 certification, the formatting of tables in the reports isn't expected.

![image](https://user-images.githubusercontent.com/6181441/40736789-d52c6822-63f3-11e8-8e38-8dabae69be05.png)

**Repro Steps** 

1. with released version of package (\\esri.com\software\Esri\Released\ArcGISforStateGovernment EnvironmentalAnalysis.zip) and daily build of Pro 2.2, unpack package
2. from Sample Models toolbox, edit / open Reporting Feature Class Information model
3. execute model and view result

**Comment by jmhauck** [comment]
Looks like a change at the arcpy level. Have emailed someone from arcpy mapping team to see if they can evaluate.

**Comment by jmhauck** [comment]
Verified with Pro 2.2 build 12813 that the fix from arcpy side resolves this issue.
